// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRWpKiYyAnToOQ4q7Lj1ZSDcziPS0MYf8',
    appId: '1:640584972417:web:be36a9782398036147b580',
    messagingSenderId: '640584972417',
    projectId: 'karatly',
    authDomain: 'karatly.firebaseapp.com',
    storageBucket: 'karatly.firebasestorage.app',
    measurementId: 'G-XFXNY28CM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuREf-s0_OcuZdHCV91dxX47qr7FDpP_M',
    appId: '1:640584972417:android:514bdf132eb4563147b580',
    messagingSenderId: '640584972417',
    projectId: 'karatly',
    storageBucket: 'karatly.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsQ12YhvNG3pPvxEvNeZ1_ugoIZ-qY7rk',
    appId: '1:640584972417:ios:e98945f8a64c461547b580',
    messagingSenderId: '640584972417',
    projectId: 'karatly',
    storageBucket: 'karatly.firebasestorage.app',
    iosBundleId: 'com.example.karatly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRWpKiYyAnToOQ4q7Lj1ZSDcziPS0MYf8',
    appId: '1:640584972417:web:b2929dba43b7785947b580',
    messagingSenderId: '640584972417',
    projectId: 'karatly',
    authDomain: 'karatly.firebaseapp.com',
    storageBucket: 'karatly.firebasestorage.app',
    measurementId: 'G-H7QQDYGEQ7',
  );
}
